### ISSUE TITLE
Companion Bitbucket Plugin stopped working

### ISSUE THREAD

**Issue by nanoq66** [mikestead/bitbucket-semver#12]
Not sure how to contact you in a different way. The Bitbucket Plugin stopped working with Bitbucket 6.x. We're happy to help out fixing, but would need access to the repo.

`2019-10-04 13:12:34,313 WARN  [ThreadPoolAsyncTaskExecutor::Thread 36]  c.a.plugin.osgi.factory.OsgiPlugin Ignoring the bean container that was just created fo
r plugin mikestead.bitbucket.bitbucket-semver. The plugin is in an invalid state, DISABLED, that doesn't support a transition to enabled. Most likely, it was d
isabled due to a timeout.
2019-10-04 13:12:35,262 ERROR [UpmAsynchronousTaskManager:thread-4] QXR6795 @1V2O9QRx792x657x0 ldgbbz 172.27.220.145 "POST /rest/plugins/1.0/ HTTP/1.1" c.a.p.m
anager.DefaultPluginManager There was an error loading the descriptor 'Semver PR Label' of plugin 'mikestead.bitbucket.bitbucket-semver'. Disabling.
java.lang.NoClassDefFoundError: com/atlassian/bitbucket/hook/repository/RepositoryMergeRequestCheck
        at java.lang.ClassLoader.defineClass1(Native Method)
        at com.atlassian.plugin.module.ClassPrefixModuleFactory.getModuleClass(ClassPrefixModuleFactory.java:44)
        at com.atlassian.plugin.module.PrefixDelegatingModuleFactory.guessModuleClass(PrefixDelegatingModuleFactory.java:145)
        at com.atlassian.plugin.module.PrefixDelegatingModuleFactory$$FastClassBySpringCGLIB$$e05be356.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at com.atlassian.stash.internal.plugin.OsgiSafeProxyProvider$1.invoke(OsgiSafeProxyProvider.java:95)
        at com.atlassian.plugin.module.PrefixDelegatingModuleFactory$$EnhancerBySpringCGLIB$$6a5e4311.guessModuleClass(<generated>)
...  com.atlassian.plugin.manager.PluginTransactionContext.wrap(PluginTransactionContext.java:63)
        at com.atlassian.plugin.manager.DefaultPluginManager.addPlugins(DefaultPluginManager.java:1115)
....
caused by: java.lang.ClassNotFoundException: com.atlassian.bitbucket.hook.repository.RepositoryMergeRequestCheck
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        ... 68 common frames omitted
`

**Comment by nanoq66** [comment]
Don't think its a big thing to do :)
https://docs.atlassian.com/bitbucket-server/javadoc/5.0.0/spi/reference/com/atlassian/bitbucket/hook/repository/RepositoryMergeRequestCheck.html
